language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
    - webapp/node_modules
before_script:
  - cd webapp
  - yarn install
  - cd ..
script:
  - echo "nothing"
deploy:
  provider: heroku
  skip_cleanup: true
  local_dir: build
  api_key: ${api_key}