language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
before_script:
  - rm -rf build
script:
  - cd webapp
  - yarn install
  - yarn build
  - cd ..
deploy:
  provider: heroku
  api_key: ${api_key}