language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
    - echo "skipping tests"
    - cd webapp
    - yarn install
    - yarn build
deploy:
  provider: heroku
  api_key: ${api_key}