language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
    - echo "skipping tests"
    - cd webapp
    - npm run build
deploy:
  provider: heroku
  api_key: ${api_key}